services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_SPI_IMPORT_ENABLED=true
      - KC_SPI_IMPORT_STRATEGY=REALM_FILE
      - KC_SPI_IMPORT_DIR=/opt/keycloak/data/import
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - "8080:8080"

  db:
    image: postgres:16.4
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crud -d crud"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: crud
      POSTGRES_PASSWORD: testecrud
      POSTGRES_DB: crud
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: flask run --host=0.0.0.0
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=crud
      - POSTGRES_PASSWORD=testecrud
      - POSTGRES_DB=crud

      - FLASK_APP=app.main

      - KEYCLOAK_SERVER=http://keycloak:8080/auth
      - KEYCLOAK_REALM=testes
      - KEYCLOAK_CLIENT_ID=crud-api
      - KEYCLOAK_CLIENT_SECRET=KX92YjfxGtW8Red8lk9aAjMPq6HZVSAr
volumes:
  postgres_data:
